baseURL = "http://examplesite.org"
disableLanguages = ["fr"]
disqusShortname = "NMSTECH"
paginate = "6"
summaryLength = "10"
theme = "NMSTECH"
title = "NMS | New Minds School"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 NMS | New Minds School "
home = "Inicio"
languageCode = "pt-br"
languageName = "Pt"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "scholarship"
name = "Bolsa de Estudos"
weight = 2
[[menu.footer]]
URL = "teacher"
name = "Professor"
weight = 5
[[menu.footer]]
URL = "notice"
name = "Notícias"
weight = 4
[[menu.footer]]
URL = "event"
name = "Eventos"
weight = 3
[[menu.footer]]
URL = "research"
name = "Pesquisa"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contato"
weight = 5
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
URL = "scholarship"
name = "Bolsa de Estudos"
parent = "Páginas"
weight = 5
[[menu.main]]
URL = "event"
name = "Eventos"
parent = "Páginas"
weight = 4
[[menu.main]]
URL = "notice"
name = "Notícia"
parent = "Páginas"
weight = 3
[[menu.main]]
URL = "teacher"
name = "teacher"
parent = "Páginas"
weight = 2
[[menu.main]]
URL = "research"
name = "Pesquisa"
parent = "Páginas"
weight = 1
[[menu.main]]
hasChildren = true
name = "Páginas"
weight = 3
[[menu.main]]
URL = "course"
name = "Curso"
weight = 2
[[menu.main]]
URL = "about"
name = "Sobre"
weight = 1
[params]
address = "R. mar das Filipinas"
author = "Ricardo"
contact_form_action = "#"
description = "Seu futuro é a nossa missão"
email = "alanzk58@gmail.com"
google_analitycs_id = ""
logo = "/images/logo_nms_new_transparent.png"
mobile = "+5511972645965"
top_header = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "/images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
